version: "3.9"
services:
 db:
  image: postgres:15
  environment:
    POSTGRES_USER: example_user
    POSTGRES_PASSWORD: example_password
    POSTGRES_DB: company_db
  volumes:
    - ./data/db:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  networks:
  - company_network
 adminer:
  image: adminer
  restart: always
  ports:
  - "8080:8080"
  networks:
  - company_network
networks:
 company_network:
  driver: bridge